# Generated by Django 5.2 on 2025-05-01 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='food_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.foodclub'),
        ),
    ]
